# Generated by Django 6.0 on 2025-12-29 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('location', models.CharField(choices=[('DUBAI', 'Dubai'), ('ABU_DHABI', 'Abu Dhabi')], max_length=20)),
                ('short_description', models.CharField(blank=True, max_length=260)),
                ('description', models.TextField(blank=True)),
                ('duration_days', models.PositiveIntegerField(blank=True, null=True)),
                ('price_from', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='AED', max_length=10)),
                ('image_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_featured', 'title'],
            },
        ),
    ]
