# Generated by Django 6.0 on 2025-12-29 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='gallery',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='highlights',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='itinerary',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='keywords',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='reviews',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='thumbnail_url',
            field=models.URLField(blank=True),
        ),
    ]
